# First Neurons

In [2]:
import numpy as np
import tensorflow as tf

In [12]:
np.random.seed(101)
tf.set_random_seed(101)

In [13]:
rand_a = np.random.uniform(0,100,(5,5))
rand_a

array([[51.63986277, 57.06675869,  2.84742265, 17.15216562, 68.52769817],
       [83.38968626, 30.69662197, 89.36130797, 72.15438618, 18.99389542],
       [55.42275911, 35.2131954 , 18.18924027, 78.56017619, 96.54832224],
       [23.23536618,  8.35614337, 60.35484223, 72.89927573, 27.62388285],
       [68.53063288, 51.78674742,  4.84845374, 13.78692376, 18.69674261]])

In [14]:
rand_b = np.random.uniform(0,100,(5,1))
rand_b

array([[99.43179012],
       [52.06653967],
       [57.87895355],
       [73.48190583],
       [54.19617722]])

In [15]:
a = tf.placeholder(tf.float32)

In [16]:
b = tf.placeholder(tf.float32)

In [17]:
add_op = a + b

In [18]:
mul_op = a * b

In [22]:
# with tf.Session() as sess:
#     add_result = sess.run(add_op, feed_dict={a:10,b:20})
#     print(add_result)

30.0


## Example Neural Network

In [44]:
n_features = 10 # 特征数量
n_dense_neurons = 3 # 隐藏层神经元数量？只有一个隐藏层？输出层神经元数量？没有隐藏层？

In [45]:
x = tf.placeholder(tf.float32,(None,n_features), name='x') # 为什么不是(n_features， None)???

In [46]:
b = tf.Variable(tf.zeros([n_dense_neurons]),name='b') # 每个神经元对应一个 bias
W = tf.Variable(tf.random_normal([n_features,n_dense_neurons])) 

** Operation Activation Function **

In [47]:
xW = tf.matmul(x,W)

In [48]:
z = tf.add(xW,b)

In [49]:
# tf.nn.relu() or tf.tanh()
a = tf.sigmoid(z)

** Varaible Initilizer! **

In [50]:
init = tf.global_variables_initializer()

In [52]:
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    sess.run(init)
    
    layer_out = sess.run(a,feed_dict={x:np.random.random([1,n_features])})
writer.close()

In [35]:
print(layer_out)

[[0.7677623  0.542005   0.95446175]]
