# SciKit Learn Preprocessing

In [3]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [4]:
data = np.random.randint(0,100,(10,2))

In [5]:
data

array([[89,  4],
       [43, 70],
       [77, 96],
       [35,  7],
       [71, 24],
       [18, 74],
       [73, 27],
       [82,  3],
       [67, 70],
       [44, 45]])

In [8]:
scaler_model = MinMaxScaler()

In [9]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [10]:
scaler_model.fit(data)

c:\users\jian\appdata\local\programs\python\python36\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [11]:
scaler_model.transform(data) # 最大值对应：1；最小值:0

array([[1.        , 0.01075269],
       [0.35211268, 0.72043011],
       [0.83098592, 1.        ],
       [0.23943662, 0.04301075],
       [0.74647887, 0.22580645],
       [0.        , 0.76344086],
       [0.77464789, 0.25806452],
       [0.90140845, 0.        ],
       [0.69014085, 0.72043011],
       [0.36619718, 0.4516129 ]])

In [12]:
import pandas as pd

In [15]:
mydata = np.random.randint(0,101,(50,4))

In [16]:
mydata

array([[ 50,  78,  60,  46],
       [ 43,  56,  67,  24],
       [ 86,  28,  16,   4],
       [ 97,  96,  72,   3],
       [ 71,  85,  42,  66],
       [ 87,  69,  75,  51],
       [ 67,  68,  91,  33],
       [ 80,  20,  76,   6],
       [ 66,  50,  68,  24],
       [ 79,  35,  33,  66],
       [  9,  96,   9,  42],
       [ 70,  58,  87,  92],
       [ 22,  88,  50,   8],
       [ 11,  19,  53,  32],
       [ 25,  24,  50,  25],
       [ 37,   0,  20,  96],
       [ 39,  70,  16,  61],
       [ 21,  61,  99,  41],
       [ 43,  20,  30,  17],
       [ 85,  27,   9,  52],
       [ 31,  14,   5,  53],
       [  8,  45,  92,  63],
       [ 67,  46,  79,  29],
       [ 82,  13,  79,  58],
       [ 36,  54,  15,  34],
       [ 69,  41,  73,  11],
       [  2,  95,  45,  12],
       [ 82,  37,   2,  60],
       [ 90,  32,  92,  93],
       [ 16,  41,  69,  76],
       [  5,  53,  68,   5],
       [ 40,  99,  28,  36],
       [ 94,  14,  69,  34],
       [ 15,   0,   1,  63],
       [ 13,  

In [21]:
df = pd.DataFrame(data=mydata,columns=['f1','f2','f3','label'])

In [22]:
df

f1  f2  f3  label
0    50  78  60     46
1    43  56  67     24
2    86  28  16      4
3    97  96  72      3
4    71  85  42     66
5    87  69  75     51
6    67  68  91     33
7    80  20  76      6
8    66  50  68     24
9    79  35  33     66
10    9  96   9     42
11   70  58  87     92
12   22  88  50      8
13   11  19  53     32
14   25  24  50     25
15   37   0  20     96
16   39  70  16     61
17   21  61  99     41
18   43  20  30     17
19   85  27   9     52
20   31  14   5     53
21    8  45  92     63
22   67  46  79     29
23   82  13  79     58
24   36  54  15     34
25   69  41  73     11
26    2  95  45     12
27   82  37   2     60
28   90  32  92     93
29   16  41  69     76
30    5  53  68      5
31   40  99  28     36
32   94  14  69     34
33   15   0   1     63
34   13  27  66      7
35    1  40  74     30
36   73  85  15      7
37   90  64  16     75
38   23  91  62     95
39   33  81  27     61
40   30  63  19     45
41  100  65  27     19
42   58  46  23     83
43   68  79  46     41
44   88  36  74     69
45    2  63  91      3
46    4  28  89     24
47   20  16  45     40
48    6  35  46     20
49   58  66  53     12

In [23]:
X = df[['f1','f2','f3']]

In [24]:
y = df['label']

In [25]:
X

f1  f2  f3
0    50  78  60
1    43  56  67
2    86  28  16
3    97  96  72
4    71  85  42
5    87  69  75
6    67  68  91
7    80  20  76
8    66  50  68
9    79  35  33
10    9  96   9
11   70  58  87
12   22  88  50
13   11  19  53
14   25  24  50
15   37   0  20
16   39  70  16
17   21  61  99
18   43  20  30
19   85  27   9
20   31  14   5
21    8  45  92
22   67  46  79
23   82  13  79
24   36  54  15
25   69  41  73
26    2  95  45
27   82  37   2
28   90  32  92
29   16  41  69
30    5  53  68
31   40  99  28
32   94  14  69
33   15   0   1
34   13  27  66
35    1  40  74
36   73  85  15
37   90  64  16
38   23  91  62
39   33  81  27
40   30  63  19
41  100  65  27
42   58  46  23
43   68  79  46
44   88  36  74
45    2  63  91
46    4  28  89
47   20  16  45
48    6  35  46
49   58  66  53

In [26]:
y

0     46
1     24
2      4
3      3
4     66
5     51
6     33
7      6
8     24
9     66
10    42
11    92
12     8
13    32
14    25
15    96
16    61
17    41
18    17
19    52
20    53
21    63
22    29
23    58
24    34
25    11
26    12
27    60
28    93
29    76
30     5
31    36
32    34
33    63
34     7
35    30
36     7
37    75
38    95
39    61
40    45
41    19
42    83
43    41
44    69
45     3
46    24
47    40
48    20
49    12
Name: label, dtype: int32

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [29]:
X_train.shape

(33, 3)

In [30]:
X_test.shape

(17, 3)